### ISSUE TITLE
String index out of Bounds Exception with input fasta.

### ISSUE THREAD

**Issue by anoronh4** [antigenomics/arda#55]
I am getting a string index out of bounds exception with migmap-1.0.2. Here's the error:

```
Exception in thread "Thread-14" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at com.antigenomics.migmap.blast.PSegmentSearcher.searchLeft(PSegmentSearcher.groovy:80)
	at com.antigenomics.migmap.blast.PSegmentSearcher.search(PSegmentSearcher.groovy:37)
	at com.antigenomics.migmap.blast.PSegmentSearcher$search.call(Unknown Source)
	at com.antigenomics.migmap.blast.BlastInstance.createReadMapping(BlastInstance.groovy:128)
	at com.antigenomics.migmap.blast.BlastInstance.take(BlastInstance.groovy:209)
	at com.antigenomics.migmap.pipeline.Pipeline$2.run(Pipeline.groovy:84)
	at java.lang.Thread.run(Thread.java:748)
```

This is error is reproducible. In all honesty I don't think this is an ideal dataset. We tried something new so we're not sure if it worked. Even so, this error tells us nothing about how to fix it. My command is:

/path/to/migmap-1.0.2/migmap --data-dir /path/to/directory --blast-dir /path/to/migmap-1.0.2/ncbi-igblast-1.7.0/bin -p 8 -R TRB,TRD -S human --details fr1nt,cdr1nt,fr2nt,cdr2nt,fr3nt,fr4nt,contignt,fr1aa,cdr1aa,fr2aa,cdr2aa,fr3aa,fr4aa,contigaa /path/to/sample.contig.fasta sample_clones.migmap.xls

Some samples in this dataset worked, others did not. i do not see any empty fasta entries in the input. 

Any help you can offer is greatly appreciated! Thanks!

**Comment by bernt-matthias** [comment]
Similar problem here:

```
[Wed Nov 18 16:28:50 GMT 2020 MIGMAP +00m00s] Annotating variable segments.
Exception in thread "Thread-0" java.lang.StringIndexOutOfBoundsException: String index out of range: -70
	at java.base/java.lang.String.substring(String.java:1841)
	at java_lang_String$substring$6.call(Unknown Source)
	at com.antigenomics.migmap.blast.BlastInstance.createReadMapping(BlastInstance.groovy:157)
	at com.antigenomics.migmap.blast.BlastInstance.take(BlastInstance.groovy:209)
	at com.antigenomics.migmap.genomic.SegmentDatabase$1.run(SegmentDatabase.groovy:147)
	at java.base/java.lang.Thread.run(Thread.java:834)
[Wed Nov 18 16:28:54 GMT 2020 MIGMAP +00m04s] Fully annotated 23 of 303 segments.
[Wed Nov 18 16:28:54 GMT 2020 MIGMAP +00m04s] Analyzing sample in.fa
[Wed Nov 18 16:28:54 GMT 2020 MIGMAP +00m04s] Started analysis
[Wed Nov 18 16:28:54 GMT 2020 MIGMAP +00m04s] Loaded 1 reads. 
Exception in thread "Thread-2" java.lang.RuntimeException: No reference markup, it seems you're running on an unnatotated segment database, forgot factory.annotateV()? :)
	at com.antigenomics.migmap.mapping.ReadMappingDetailsProvider$ReadMappingDetails.<init>(ReadMappingDetailsProvider.groovy:90)
	at com.antigenomics.migmap.mapping.ReadMappingDetailsProvider.getDetails(ReadMappingDetailsProvider.groovy:71)
	at com.antigenomics.migmap.mapping.ReadMappingDetailsProvider$getDetails.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:206)
	at com.antigenomics.migmap.mapping.ReadMappingDetailsProvider.getDetailsString(ReadMappingDetailsProvider.groovy:63)
	at com.antigenomics.migmap.io.ReadMappingOutput.put(ReadMappingOutput.groovy:40)
	at com.antigenomics.migmap.io.ReadMappingOutput.put(ReadMappingOutput.groovy)
	at com.antigenomics.migmap.pipeline.Pipeline$2.run(Pipeline.groovy:86)
	at java.base/java.lang.Thread.run(Thread.java:834)
[Wed Nov 18 16:28:54 GMT 2020 MIGMAP +00m04s] Finished analysis. Processed 1 reads, of them 100.0% mapped. Among mapped reads 100.0% passed quality filter and 100.0% passed all filters.
```

switching to openjdk 8 helped.
