### ISSUE TITLE
Infinite Loop on Processed and Exception: multiply()

### ISSUE THREAD

**Issue by Chuang1118** [antigenomics/arda#58]
Hello,
I can't get complete output using migmap.
loaded 134085 reads. Processed 133598 reads, is Infinite Loop.
So my output is incomplete.
Could you please help me correct this bug!

command-line:
$ java -jar /opt/migmap-1.0.3/migmap-1.0.3.jar -p 8 --blast-dir /opt/ncbi-igblast-1.4.0/bin/ --data-dir /opt/migmap-1.0.3/data/                 --by-read --all-alleles -R TRA,TRB,TRG,TRD -S human --details fr1nt,cdr1nt,fr2nt,cdr2nt,fr3nt,fr4nt,contignt,fr1aa,cdr1aa,fr2aa,cdr2aa,fr3aa,fr4aa,contigaa            trinity_results.fasta                 output.out

log file see below:
Exception in thread "Thread-29" java.lang.IllegalArgumentException: multiply() should be called with a number of 0 or greater not: -91
	at org.codehaus.groovy.runtime.StringGroovyMethods.multiply(StringGroovyMethods.java:2057)
	at com.antigenomics.migmap.mapping.ReadMappingDetailsProvider$ReadMappingDetails.getFr2nt(ReadMappingDetailsProvider.groovy:133)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1850)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3758)
	at com.antigenomics.migmap.mapping.ReadMappingDetailsProvider$ReadMappingDetails.getProperty(ReadMappingDetailsProvider.groovy)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:456)
	at com.antigenomics.migmap.mapping.ReadMappingDetailsProvider$_getDetailsString_closure3.doCall(ReadMappingDetailsProvider.groovy:65)
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3202)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3172)
	at org.codehaus.groovy.runtime.dgm$67.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.antigenomics.migmap.mapping.ReadMappingDetailsProvider.getDetailsString(ReadMappingDetailsProvider.groovy:65)
	at com.antigenomics.migmap.io.ReadMappingOutput.put(ReadMappingOutput.groovy:40)
	at com.antigenomics.migmap.io.ReadMappingOutput.put(ReadMappingOutput.groovy)
	at com.antigenomics.migmap.pipeline.Pipeline$2.run(Pipeline.groovy:86)
	at java.lang.Thread.run(Thread.java:748)
[Mon Sep 30 10:20:33 UTC 2019 MIGMAP +01m57s] Loaded 68506 reads. Processed 64165 reads, of them 98.68% mapped. Among mapped reads 100.0% passed quality filter and 0.21% passed all filters.
[Mon Sep 30 10:20:43 UTC 2019 MIGMAP +02m07s] Loaded 74286 reads. Processed 69720 reads, of them 98.68% mapped. Among mapped reads 100.0% passed quality filter and 0.2% passed all filters.
[Mon Sep 30 10:20:53 UTC 2019 MIGMAP +02m17s] Loaded 79905 reads. Processed 75153 reads, of them 98.69% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:21:03 UTC 2019 MIGMAP +02m27s] Loaded 85472 reads. Processed 80609 reads, of them 98.71% mapped. Among mapped reads 100.0% passed quality filter and 0.2% passed all filters.
[Mon Sep 30 10:21:13 UTC 2019 MIGMAP +02m37s] Loaded 90383 reads. Processed 86087 reads, of them 98.73% mapped. Among mapped reads 100.0% passed quality filter and 0.2% passed all filters.
[Mon Sep 30 10:21:23 UTC 2019 MIGMAP +02m47s] Loaded 95627 reads. Processed 91495 reads, of them 98.72% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:21:33 UTC 2019 MIGMAP +02m57s] Loaded 100999 reads. Processed 96698 reads, of them 98.73% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:21:43 UTC 2019 MIGMAP +03m07s] Loaded 106793 reads. Processed 102036 reads, of them 98.72% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:21:53 UTC 2019 MIGMAP +03m17s] Loaded 112124 reads. Processed 107610 reads, of them 98.72% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:22:03 UTC 2019 MIGMAP +03m27s] Loaded 118165 reads. Processed 113003 reads, of them 98.74% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:22:13 UTC 2019 MIGMAP +03m37s] Loaded 123309 reads. Processed 118707 reads, of them 98.73% mapped. Among mapped reads 100.0% passed quality filter and 0.18% passed all filters.
[Mon Sep 30 10:22:23 UTC 2019 MIGMAP +03m47s] Loaded 128729 reads. Processed 124099 reads, of them 98.73% mapped. Among mapped reads 100.0% passed quality filter and 0.18% passed all filters.
[Mon Sep 30 10:22:33 UTC 2019 MIGMAP +03m57s] Loaded 134085 reads. Processed 129506 reads, of them 98.74% mapped. Among mapped reads 100.0% passed quality filter and 0.18% passed all filters.
[Mon Sep 30 10:22:43 UTC 2019 MIGMAP +04m07s] Loaded 134085 reads. Processed 133598 reads, of them 98.74% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:22:53 UTC 2019 MIGMAP +04m17s] Loaded 134085 reads. Processed 133598 reads, of them 98.74% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:23:03 UTC 2019 MIGMAP +04m27s] Loaded 134085 reads. Processed 133598 reads, of them 98.74% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:23:13 UTC 2019 MIGMAP +04m37s] Loaded 134085 reads. Processed 133598 reads, of them 98.74% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:23:23 UTC 2019 MIGMAP +04m47s] Loaded 134085 reads. Processed 133598 reads, of them 98.74% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.
[Mon Sep 30 10:23:33 UTC 2019 MIGMAP +04m57s] Loaded 134085 reads. Processed 133598 reads, of them 98.74% mapped. Among mapped reads 100.0% passed quality filter and 0.19% passed all filters.

**Comment by preinink-gadeta** [comment]
Hi, 
I running into the same problem, any help with this problem would be useful.

**Comment by LukeHebert** [comment]
I'm getting a very similar java/thread/multiply() exception. If I run MiGMAP _**without**_ the "--by-read" command, this exception occurs only once at the very end of mapping and doesn't seem to prevent the annotated reads from being written succesfully. However, if I _**do**_ use that "--by-read" argument, I get tons of these exceptions.
